### ISSUE TITLE
Authentication not working for some reason

### ISSUE THREAD

**Issue by grisaitis** [hickford/git-credential-oauth#13]
probably making a simple mistake but no idea how to make this work:

Steps I took:
1. downloaded the release and extracted the binary to `~/.local/bin`, which is in my `$PATH`
2. configured as per README (`git config --global --unset-all credential.helper`, etc. )
4. did `git push` for a repo
5. opened the URL
6. granted this repo access to my account and organization
7. re-opened the URL... following screen shows up
8. retry `git push`
9. open URL... same thing

my environment:
- on saturn cloud, inside a docker container
- ubuntu 20.04
- bash
- git version 2.25.1

`~/.gitconfig` has:

```
[credential]
        helper = cache --timeout 7200
        helper = oauth
```

this tool looks amazing. any help appreciated to make it work in my environment!

```
jovyan@w-grisa-dsc-089fe175f06e472ead0ac4e1a13a0b42-5754d6fd8-dsvwq:~/workspace$ git push -u origin main
Please complete authentication in your browser...
https://github.com/login/oauth/authorize?client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&code_challenge=xxxxxxxxxxxxxxxxxxxx&code_challenge_method=S256&redirect_uri=http%3A%2F%2F127.0.0.1%3A34009&response_type=code&scope=repo+gist+workflow&state=xxxxxxxxxxxxxxxxxxxx%3D%3D
2023/01/21 23:48:15 exec: "open": executable file not found in $PATH
Username for 'https://github.com':
```

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/908970/213894640-d79c08e2-f7ec-499d-a094-7b54a75b5963.png">

**Comment by hickford** [comment]
Hello first user to make contact!

> exec: "open": executable file not found in $PATH

This fatal error closes the application local and server. I mistakenly assumed `/usr/bin/open` to be universal. Try installing package `xdg-utils`.

I'll relax the assumption.

**Comment by grisaitis** [comment]
haha hello! thank you for the prompt reply (more prompt than this one).

i'll try this soon and circle back!
