### ISSUE TITLE
Mention secrets in README

### ISSUE THREAD

**Issue by shyim** [hickford/git-credential-oauth#23]
Hey,

It would be cool if you could explain about the hard-code client id and client secrets in the README and that they are harmless?
I never saw someone publishing the client id and client secret of oauth apps and was first worried 😅

**Comment by hickford** [comment]
@shyim Does https://github.com/hickford/git-credential-oauth/commit/6d4dd40011232ad6e921198cf8eb8bd615311501 explain clearly? 

https://github.com/hickford/git-credential-oauth/blob/6d4dd40011232ad6e921198cf8eb8bd615311501/main.go#L45-L50

**Comment by shyim** [comment]
Sounds good thanks!
