### ISSUE TITLE
Command/flag to output the version

### ISSUE THREAD

**Issue by shyim** [hickford/git-credential-oauth#24]
I would like add an small test that the executeable runs for packaging. So I would need some flag/command. [See example from Nix](https://nixos.org/manual/nixpkgs/unstable/#tester-testVersion)

**Comment by hickford** [comment]
Users can run `git-credential-oauth -verbose` to see the application version, printed to standard *error*.  This might not work for your packaging test, but I'm loath to complicate it further.

**Comment by shyim** [comment]
I can understand :)
