### ISSUE TITLE
 Git can't find the application

### ISSUE THREAD

**Issue by aotongarcia** [hickford/git-credential-oauth#36]
Hey there, I came across this repository through [gitea/issues/25189](https://github.com/go-gitea/gitea/issues/25189). I tried following your instructions but I can't get Git to find the application. I am on a Windows host, both `git` and `git-credential-oauth.exe` are in my system path. However, when following the repo instructions 
```
Then test that Git can find the application: 
git credential-oauth
```` 
I get the following error 
```
git credential-oauth configure
git: 'credential-oauth' is not a git command. See 'git --help'.
```

If I run `git-credential-oauth configure --verbose` I see it actually making changes to my `.gitconfig` file. Is there something I am missing?

**Comment by hickford** [comment]
> both `git` and `git-credential-oauth.exe` are in my system path

Are `git.exe` and `git-credential-oauth.exe` in the same directory? You can check with `where git` and `where git-credential-oauth`.  I recall there's some subtlety about the security of Git running a command in a different directory.

A workaround is to edit credential.helper in `.gitconfig` to specify the absolute path to git-credential-oauth.

**Comment by aotongarcia** [comment]
They are not in the same path, I didn't think to even do that - let me give it a try

**Comment by aotongarcia** [comment]
Looks like we are in business!

![image](https://github.com/hickford/git-credential-oauth/assets/86726660/c884a42c-8d38-413b-b60a-ceb0c06c1022)

I'm happy to create a PR to update `README.md` for the Windows instructions :)

**Comment by hickford** [comment]
>  I recall there's some subtlety about the security of Git running a command in a different directory.

I wonder if this is specific to Git for Windows or could also apply on Linux? I can't find any documentation.
