### ISSUE TITLE
Possible to specify credential helper as an env var?

### ISSUE THREAD

**Issue by hydrajump** [hickford/git-credential-oauth#43]
Is it possible to temporarily specify `git-credential-oauth` as the credential helper like `GIT_SSH_COMMAND`, but for HTTPS?

I'd like to be able to do a one-time similar to this:

```
GIT_HTTPS_COMMAND=git-credential-oauth command
```

At the moment I'm creating the `.gitconfig` and then deleting the file. It works, but thought I'd ask if there's a better way :)

**Comment by hickford** [comment]
You can specify any Git configuration setting temporarily following https://git-scm.com/docs/git#Documentation/git.txt--cltnamegtltvaluegt

    git -c credential.helper=oauth push

or ignoring ignoring other credential helpers:

    git -c credential.helper= -c credential.helper=oauth push

May I ask why you want to do this? https://xyproblem.info/

More convenient would be to set Git configuration specific to one repository:

    git config --local credential.helper=oauth

or specific to one host:

    git config --global credential.https://example.com.helper=oauth

**Comment by hydrajump** [comment]
Thank you @hickford! Your first command worked :)
The reason I wanted to do this without creating a `.gitconfig` is that I'm running this on a host that is diskless and I wanted to be able to use OAUTH instead of creating a GitHub personal access token.

**Comment by hickford** [comment]
Better surely to configure a storage helper such as cache so you don't have to reauthenticate so often?

    git -c credential.helper="cache --timeout 3600" -c credential.helper=oauth push

Equivalently

    [credential]
    helper = cache --timeout 3600
    helper = oauth

Equivalently

    git config --global --add credential.helper "cache --timeout 3600"
    git config --global --add credential.helper oauth

**Comment by hydrajump** [comment]
Just wanted to thank you again! This has worked very well in the last week :)
