### ISSUE TITLE
What happens when using storage helper osxkeychain?

### ISSUE THREAD

**Issue by hydrajump** [hickford/git-credential-oauth#44]
>  This happens because git-credential-osxkeychain doesn't store attributes [password_expiry_utc](https://git-scm.com/docs/git-credential#Documentation/git-credential.txt-codepasswordexpiryutccode) and [oauth_refresh_token ](https://git-scm.com/docs/git-credential#Documentation/git-credential.txt-codeoauthrefreshtokencode). These are necessary for OAuth token refresh.

_Originally posted by @hickford in https://github.com/hickford/git-credential-oauth/issues/42#issuecomment-1849885415_
          
Does this mean that the OAuth token never expires when using the default configuration below?

```
[credential]
	helper = osxkeychain
	helper = oauth
```

**Comment by hickford** [comment]
> periodically I have to run the git command twice

You'll find that authentication fails once every two hours, because Git tries to use an expired token. Git immediately erases  the invalid credential, so repeating the command will generate a fresh OAuth token and succeed. 

This problem doesn't occur with GitHub because GitHub's OAuth tokens never expire.

**Comment by hydrajump** [comment]
To make sure I understand what you're saying:

>You'll find that authentication fails once every two hours,
This is only applicable when the `cache` helper is used and a timeout of `7200` is set, correct?

>This problem doesn't occur with GitHub because GitHub's OAuth tokens never expire.
Right when the `osxkeychain` is used to store the oauth token it never expires. This was what I wanted to confirm when I created this issue :)

AFAICT it doesn't make sense to combine the `cache` and `osxkeychain` helpers. Do you agree?

**Comment by hickford** [comment]
A fix to credential-osxkeychain is in review https://github.com/gitgitgadget/git/pull/1667 https://lore.kernel.org/git/pull.1667.git.1708212896.gitgitgadget@gmail.com/
