### ISSUE TITLE
GitLab authorize app multiple times in a day

### ISSUE THREAD

**Issue by Bankers88** [hickford/git-credential-oauth#45]
Hi,

We use GitLab Saas and the git-credential-oauth, and multiple times a day, we have to authorize this app again. I assumed that this was a one-time configuration. Is this as designed, or can you explain this to me?

```
git pull
Please complete authentication in your browser...
https://gitlab.com/oauth/authorize?client_id=[client]&code_challenge=[code_c]code_challenge_method=[ccm]&redirect_uri=[uri]=code&scope=read_repository+write_repository&state=[state]
``` 

This opens a browser to approve yet again the git-credential-oauth app in GitLab. See attachment for a screenshot.

<img width="528" alt="Authorize-git-credential-oauth" src="https://github.com/hickford/git-credential-oauth/assets/23034005/c151f713-2504-4adf-9194-1f611c0bcd7c">

If you need more information please let me know.

Thanks,  

Rob

**Comment by hickford** [comment]
What's your configuration? 

    git config --global --get-all credential.helper

**Comment by Bankers88** [comment]
git config --global --get-all credential.helper
```
cache --timeout 7200
oauth
``` 
What platform are you using?
GitLab Saas

Which versions are you running?
```
git version
git version 2.43.0

git-credential-oauth -verbose
git-credential-oauth 0.11.0
```

**Comment by hickford** [comment]
Thanks. Which operating system are you running?

**Comment by hickford** [comment]
"cache --timeout 7200" means your credentials are saved for 2 hours :

Try increasing the timeout to 20 hours or even longer:

```
git config --global --unset-all credential.helper
git config --global --add credential.helper "cache --timeout 72000" # 20 hours
git config --global --add credential.helper oauth
```

If you know any Mac OS C developers, encourage them to collaborate on git-credential-osxkeychain https://github.com/hickford/git-credential-oauth/issues/42#issuecomment-1849885415

**Comment by stefangweichinger** [comment]
I see the same behavior. It seems it's enough/better to only add "write-repository" permissions.
At least only "read-repository" gets added to `~/.gitconfig` in my case. I am still trying things, adding my 2 cents for now ...

**Comment by hickford** [comment]
https://github.com/hickford/git-credential-oauth/commit/9423940dcb2b3483856d7151f83f2da5f7ed46f5 increases default cache timeout to fix hours
