### ISSUE TITLE
error not found when called git credential-oauth in ubuntu 20.04

### ISSUE THREAD

**Issue by amri-id** [hickford/git-credential-oauth#46]
i am using ubuntu 20.04 then what i did are:
1. i download 0.11 for arm64
2. paste the exe file in usr/bin
3. call git credential-oauth

the error is:
```
/usr/bin/git-credential-oauth: 1: ELF��@�@8@@@@PP���ddT�#T�#$%%h�h�LMM@-��Q�tT�#]%$��: not found
/usr/bin/git-credential-oauth: 5: Syntax error: ")" unexpected
```

what is wrong?? is this support ubuntu 20.04?
please help, thank you

**Comment by hickford** [comment]
If you're familiar with [Ubuntu PPAs](https://launchpad.net/ubuntu/+ppas), you can also install a package from PPA https://launchpad.net/~hickford/+archive/ubuntu/git-credential-oauth

     sudo add-apt-repository ppa:hickford/git-credential-oauth
     sudo apt update
     sudo apt install git-credential-oauth

**Comment by amri-id** [comment]
> If you're familiar with [Ubuntu PPAs](https://launchpad.net/ubuntu/+ppas), you can also install a package from PPA https://launchpad.net/~hickford/+archive/ubuntu/git-credential-oauth
> 
> ```
>  sudo add-apt-repository ppa:hickford/git-credential-oauth
>  sudo apt update
>  sudo apt install git-credential-oauth
> ```

you are right, i thought my ubuntu was arm64.

i followed your instruction but i got this error in the third step,
```
The following packages have unmet dependencies:
 git-credential-oauth : Depends: libc6 (>= 2.34) but 2.31-0ubuntu9.14 is to be installed
E: Unable to correct problems, you have held broken packages.
```

does it mean i must install/update libc6?

**Comment by hickford** [comment]
> i followed your instruction but i got this error in the third step,

@amri-id Try again. I've rebuilt the package for Ubuntu jammy with the correct libc6 dependency

**Comment by amri-id** [comment]
> > i followed your instruction but i got this error in the third step,
> 
> @amri-id Try again. I've rebuilt the package for Ubuntu jammy with the correct libc6 dependency

this is the error now from step 3,
i tried again from step 1 but this error still occurred

```
E: Unable to locate package git-credential-oauth
```

**Comment by hickford** [comment]
@amri-id Try once more

**Comment by hickford** [comment]
@amri-id Is your problem solved?

**Comment by amri-id** [comment]
> @amri-id Is your problem solved?

yes, I close it now.
but i have a question.
can i make it as permanent? or maybe for a year??
