### ISSUE TITLE
Bitbucket oauth is requesting for all git commands

### ISSUE THREAD

**Issue by leonardopn** [hickford/git-credential-oauth#49]
Hello. I'm using the Bitbucket oauth with the version 0.11.1, 
My problem is: For any git command, the windows with oauth is open. The auth is correct, but apparently, is not saving in cache.

My git global configs:

```
[user]
	email = leonardocps9@protonmail.com
	name = Leonardo Petta do Nascimento
[pull]
	ff = only
[credential]
	helper = cache --timeout 7200
	helper = oauth
```

And a video with the problem:

https://github.com/hickford/git-credential-oauth/assets/39427966/e5054b63-722d-49e8-a586-ad057e280663

But if i use oauth in device mode, a box is opening and i insert my password. After this, my auth is cached.

https://github.com/hickford/git-credential-oauth/assets/39427966/2e858921-b80f-4e26-adee-05d6be2e19c8

**Comment by hickford** [comment]
Which operating system are you using?

Try debugging with `oauth -verbose` https://github.com/hickford/git-credential-oauth/blob/main/README.md#debugging

**Comment by hickford** [comment]
Check which helpers you have configured with

     git config --get-all credential.helper

It's possible you have extra helpers in a system config.

**Comment by leonardopn** [comment]
I'm using manjaro linux.

```bash
# uname -a
Linux PC-Leonardo 6.1.80-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Mar  1 18:09:53 UTC 2024 x86_64 GNU/Linux
```

Using verbose flag

![image](https://github.com/hickford/git-credential-oauth/assets/39427966/11c96044-6810-4044-8453-1783289f1033)

My credential configs:

![image](https://github.com/hickford/git-credential-oauth/assets/39427966/71f0cfe3-c4f0-4fae-b960-9c83e3a5f789)

With github is working normally

**Comment by hickford** [comment]
Aha! The input includes your personal username, so credential-cache won't find the OAuth credential with username x-token-auth.

What's your remote? `git remote -v`. Try removing your username from the URL.

**Comment by leonardopn** [comment]
Eureka!!

Wow, was exactly this the problem haha.

I removed my username from the fetch url and now, everthings works. Thank you very much @hickford.

About your observation:
> Perhaps the app should print a warning in this case.

I think what a warning it would be nice.
