### ISSUE TITLE
Output more information when git-credential-oauth fails

### ISSUE THREAD

**Issue by voltagex** [hickford/git-credential-oauth#50]
I'm troubleshooting issues with my local Forgejo setup, and unfortunately all I get back is "Verify" from the remote, followed by a password prompt.

I think with `-verbose` or `GIT_TRACE`, git-credential-oauth should display more information as to why something failed.

**Comment by hickford** [comment]
Good idea!

**Comment by hickford** [comment]
Fixed in https://github.com/hickford/git-credential-oauth/commit/c1767ed57c7340657a2d234b60b16a1d1e894d4f

**Comment by voltagex** [comment]
I don't think this solves my particular issue but I can open another issue if needed.
