### ISSUE TITLE
Different (bigger) scope of permissions in github vs gitlab

### ISSUE THREAD

**Issue by rodoviario** [hickford/git-credential-oauth#54]
I am using regulary git-credentaial-oauth with gitlab. Yesterday I was going to clone a github.com project and noted a bigger scope there to accept of the app, and no way to reduce or limit it to the bare minimum necessary.

Actually, for doing a git clone of the https URL I guess that no auth have to be necessary. Unless you later try to do a push, and in that case

Is there a way to reduce the scope when pulling from github.com? 
* Remove gists (read/write)
* Reduce scope (perhaps to the specific repo)
* Remove organizations (or make them optional)
* Remove workflow

And if there is not, at least is there a way to configure it to ignore github.com but keep working for gitlab.com?

echo url=https://gitlab.com | git credential fill
![gitlab](https://github.com/hickford/git-credential-oauth/assets/4974682/7ab3d18d-4c51-4bdf-80f0-40bb2e67c826)

echo url=https://github.com | git credential fill
![github](https://github.com/hickford/git-credential-oauth/assets/4974682/cf5c1a65-ee41-48ff-a95f-e6409a77979e)

**Comment by hickford** [comment]
The default scope for GitHub is:

https://github.com/hickford/git-credential-oauth/blob/baef999395425f9c7c7ce616e72243a855aa6244/main.go#L48

You can customise the scope as you prefer https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps

     git config --global credential.https://github.com.oauthScopes repo

You can

**Comment by hickford** [comment]
> specific repo

Separately to OAuth, you might be interested in GitHub's fine-grained personal access tokens https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token
