### ISSUE TITLE
About latest release

### ISSUE THREAD

**Issue by chenrui333** [hickford/git-credential-oauth#55]
👋 looks like 0.11.3 tag is not tagged as latest release, any idea why? Thanks.

![image](https://github.com/hickford/git-credential-oauth/assets/1580956/80b2a10f-3280-4620-80fb-6435dd2cfd5c)

relates to https://github.com/Homebrew/homebrew-core/pull/170670

**Comment by hickford** [comment]
v0.11.3 released with goreleaser https://github.com/hickford/git-credential-oauth/releases/tag/v0.11.3
