### ISSUE TITLE
Using git credential manager oauth2 id

### ISSUE THREAD

**Issue by shyim** [hickford/git-credential-oauth#56]
With the current oauth2 app, I need to request for access at some orgs.

<img width="1037" alt="image" src="https://github.com/hickford/git-credential-oauth/assets/6224096/9f8b43f3-9386-418d-a08b-aafe6acaf444">

The Git Credential Manager seems to be allowed by many orgs by default. Maybe it makes sense to switch to that client id by default if possible? 🤔

**Comment by hickford** [comment]
You can customise the OAuth client id and secret for any host using config:

    git config --global credential.https://example.com.oauthClientId
    git config --global credential.https://example.com.oauthClientSecret
