### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by KraXen72** [hickford/git-credential-oauth#57]
Hi! is it possible to configure this to work with multiple accounts? if so, how? I would like to avoid SSH if possible, HTTPS just works on more public networks. Thanks!

**Comment by hickford** [comment]
Which host?

Easy with GitHub -- set the username in the repo:

     git config credential.username user1

**Comment by hickford** [comment]
Small improvement in https://github.com/hickford/git-credential-oauth/commit/433448941349b18aac69b08f34c1092f7a4db54e

**Comment by KraXen72** [comment]
github and gitlab
for now, i have resolved it by using GCM and username@github.com/author/repo type urls.
