### ISSUE TITLE
Support Passing a Different Host/Port URL

### ISSUE THREAD

**Issue by saadparwaiz1** [hickford/git-credential-oauth#59]
Currently, redirect url if passed is used to start the http server. I was hoping for a small enhancement to support passing in a server url which if specified is used and the redirectUrl is just used in the oauth request.

**Comment by saadparwaiz1** [comment]
I can create a quick pr if you sre happy to support this :)

**Comment by hickford** [comment]
What's the motivation?

**Comment by saadparwaiz1** [comment]
I'm planning on hosting a code server. And I want to try and configure it to connect GitHub/gitlab via oauth. In that scenario, the whole plan would be start the http server at a 0.0.0.0 host with some port X. 

This host and port will be mapped to a redirect url i.e. https://some-code.com. Now when GitHub/gitlab send the redirect url back it'll automatically work :)

**Comment by hickford** [comment]
Thanks for the explanation. That's somewhat different to the intention of this project, so I'll close as not planned. I hope you can make something similar work.
