### ISSUE TITLE
Gitlab.com Browserless -device flag "endpoint missing DeviceAuthURL"

### ISSUE THREAD

**Issue by rlee4advancelocal** [hickford/git-credential-oauth#60]
The README.md suggests that the -device flag is supported for gitlab.com.
However, attempting this, I receive the following error:

```
git clone https://gitlab.com/XXX/XXXX/xxxx.git
Cloning into 'xxxxx'...
2024/08/01 14:05:57 endpoint missing DeviceAuthURL
Username for 'https://gitlab.com': ^C
```

I've also tried setting up gitlab.com with instructions labeled as "Custom hosts" with the same result.

I am using the git-credential-oauth package provided by apt in Ubuntu 24.04.
I have also tried compiling the go binary from the repo to still the same effect.

**Comment by hickford** [comment]
gitlab.com device auth works for me. Double check everything?

You'll need git-credential-oauth version 0.13 or later. Try uninstall the older package.

And to set config  

    git config --global credential.https://gitlab.com.oauthDeviceAuthURL /oauth/token

**Comment by hickford** [comment]
Corrected README

https://github.com/hickford/git-credential-oauth/commit/1e9f4f0806cec46458fc0c086314fbbc44ecad88

**Comment by rlee4advancelocal** [comment]
Based on the updated README, adding the configuration explicitly for the device auth works!
`git config --global credential.https://gitlab.com.oauthDeviceAuthURL /oauth/authorize_device`

Without the added configuration, I am still receiving `endpoint missing DeviceAuthURL`.
Thank you for the update!

**Comment by EliezerB123** [comment]
Is it possible to do connect like this with version 12.1, or do we need version 13.0?

**Comment by hickford** [comment]
@EliezerB123 Yes you'll need 0.13.0 or later

https://github.com/hickford/git-credential-oauth/issues/60#issuecomment-2264124659
