### ISSUE TITLE
v0.13.2 source tarball checksum changed

### ISSUE THREAD

**Issue by stefanb** [hickford/git-credential-oauth#61]
👋  While building
* https://github.com/Homebrew/homebrew-core/pull/175310 

we noticed, that the source tarball hash at tag `v0.13.2` has changed from `06da9103faaadf1e0d1f7ae9758f7193828fc9d7b3de246fcd8ef889450c5639` (since https://github.com/Homebrew/homebrew-core/pull/180639 ) to current `ee894f81c63dbfc9ff7fc59affce3cedca85e9ef3d7b10ea6f0af86e712418d7`:

https://github.com/Homebrew/homebrew-core/actions/runs/10375471363/job/28727784153?pr=175310#step:3:7976

````
  ==> Downloading from https://codeload.github.com/hickford/git-credential-oauth/tar.gz/refs/tags/v0.13.2
  Downloaded to: /Users/brew/Library/Caches/Homebrew/downloads/d7e47f95a25d972c964539b918890c1dd830c260a9b3db8a95aef3ff332c209b--git-credential-oauth-0.13.2.tar.gz
  SHA256: ee894f81c63dbfc9ff7fc59affce3cedca85e9ef3d7b10ea6f0af86e712418d7
  Warning: Formula reports different sha256: 06da9103faaadf1e0d1f7ae9758f7193828fc9d7b3de246fcd8ef889450c5639
````

The most likely cause is that the tag `v0.13.2` was moved, but please confirm this was done intentionally before we accept is as such in 
* https://github.com/Homebrew/homebrew-core/pull/181402

**Comment by hickford** [comment]
Yes the tag moved

**Comment by carlocab** [comment]
Thanks for the confirmation!

You might already be aware, but the Git docs have some pretty strong words about re-tagging: https://www.git-scm.com/docs/git-tag#_on_re_tagging

It's generally not very nice to your downstream consumers, and has some security implications. If you decide to re-tag again in the future, we'd appreciate it if doing so was announced more publicly (as also suggested in the Git docs linked above).
