### ISSUE TITLE
Better cross environment support

### ISSUE THREAD

**Issue by robhicks** [hickford/git-credential-oauth#64]
Thanks for git-credential-oauth!! 

I work on several different headless projects in different environments, including raspberry-pi, linux and WSL2.  I use one account in GitHub, with 4 different enterprises.

I am constantly being required to reauthenticate when switching environments. 

Is there something that could be done to prevent having to reauthenticate in this scenario?

**Comment by hickford** [comment]
What storage do you use? `git config --get-all credential.helper`

These troubleshooting instructions may help you https://github.com/hickford/git-credential-oauth/blob/main/README.md#troubleshooting
