### ISSUE TITLE
Missing version number on Debian

### ISSUE THREAD

**Issue by Cchenzishi** [hickford/git-credential-oauth#66]
I install and use oauth on  **debian 12**, but it is not work on my **debian 12** to connect my gitea sites. So i try to update git version to 1.47, update gitea version from 1.21.11 (a correct version) to 1.22.3, But it is still not work. 

Untill i build sources code by hand, it work, i wasted a beautiful day to fix it. But it is not even a question.

**just because debian 12 bookworm software package version is 0.4.2 and gitea support need newer.**

I've never paid attention to the version number while using and testing oauth, because it do not output the version infomation at help and verbose on start.

I see the getVersion() in main.go, but i dont ensure that is not work.

So please add version info or fix it.

Thanks for you, wish you have a nice day.

**Comment by hickford** [comment]
Fixed in Debian packaging 

https://salsa.debian.org/go-team/packages/git-credential-oauth/-/commit/0e715abd6c7b6c776d09c28c0faf77007e596f1b
